import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    // .karajan/ is managed tooling (regenerated by `kj harden`), not app source
    ignores: ['dist/', '.astro/', 'private/', '.karajan/'],
  },
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2025,
      sourceType: 'module',
    },
    rules: {
      'no-var': 'error',
      'prefer-const': 'error',
      eqeqeq: 'error',
    },
  },
  {
    // Scripts de Node (herramientas de desarrollo, no código de la app)
    files: ['scripts/**/*.mjs', '*.config.js', '*.config.mjs'],
    languageOptions: {
      globals: {
        process: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        setTimeout: 'readonly',
      },
    },
  },
  {
    // Código de navegador (componentes Lit, scripts de página)
    files: ['src/**/*.js'],
    languageOptions: {
      globals: {
        console: 'readonly',
        customElements: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        localStorage: 'readonly',
        navigator: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        window: 'readonly',
      },
    },
  },
];
